# Generated by Django 2.1.7 on 2019-03-15 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
        ('carriers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airports.Airport')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriers.Carrier')),
            ],
        ),
        migrations.CreateModel(
            name='Delays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_aircraft', models.IntegerField()),
                ('weather', models.IntegerField()),
                ('security', models.IntegerField()),
                ('national_aviation_system', models.IntegerField()),
                ('carrier', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled', models.IntegerField()),
                ('on_time', models.IntegerField()),
                ('total', models.IntegerField()),
                ('delayed', models.IntegerField()),
                ('diverted', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MinutesDelayed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_aircraft', models.IntegerField()),
                ('weather', models.IntegerField()),
                ('carrier', models.IntegerField()),
                ('security', models.IntegerField()),
                ('total', models.IntegerField()),
                ('national_aviation_system', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriers.Delays')),
                ('flights', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriers.Flights')),
                ('minutes_delayed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriers.MinutesDelayed')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='carrierdata',
            name='statistics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriers.Statistics'),
        ),
        migrations.AddField(
            model_name='carrierdata',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriers.Time'),
        ),
    ]
